### PR TITLE
modify compiler directives for linux compilation

### PR DESCRIPTION
**Pull request by larssp**
I currently try to compile BEMRosetta on Ubuntu Linux and think these two adjustments need to be made.

### CODE REVIEW

**Comment by izabala123** [comment]
Hi larssp. I have fixed this problem and another one in aqwa. Thank you.

**Comment by izabala123** [comment]
Hi larssp. To acknowledge your contribution, if you want, reopen your commits for me to integrate them, so that they are recorded.

**Comment by larssp** [comment]
Thanks @izabala123 . You included my handle in your commit message and I was able to compile BEMRosetta now.  
So I'm good 👍

**Comment by izabala123** [comment]
Thank you very much for vour review!

**Pull request closed without merging**
